name: Build and deploy Node.js app to Azure Web App - jmBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install specific npm version
        run: npm install -g npm@10.8.1

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: Build the project
        run: npm run build

      - name: List files in the root directory
        run: ls -la

      - name: List files in the dist directory
        run: ls -la dist

      - name: List files in the node_modules directory
        run: ls -la node_modules

      - name: List files in the node_modules/.bin directory
        run: ls -la node_modules/.bin

      - name: Ensure correct permissions for all files
        run: chmod -R 755 .

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C88A70845E694DD5921A1D20FAD296EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C734955474F7464BAAC08653A1FA9C94 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C28A19FF24934E94891F8A1DBF9E25D3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jmBackend'
          slot-name: 'Production'
          package: .
          startup-command: 'npm run start:prod'

      - name: List files in the deployed directory
        run: ls -la

      - name: Check running Node.js version
        run: node -v

      - name: Check running npm version
        run: npm -v

      - name: Verify node_modules in deployed directory
        run: ls -la node_modules

      - name: Verify dist directory in deployed directory
        run: ls -la dist
